services:
  strapi:
    image: ghcr.io/${REPO_OWNER:-mfaris2002}/portfolio-strapi:latest
    container_name: portfolio-strapi
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      STRAPI_URL: ${STRAPI_URL:-http://localhost:1337}
      # Required keys for Strapi Production
      APP_KEYS: ${APP_KEYS:-toBeModified1,toBeModified2}
      API_TOKEN_SALT: ${API_TOKEN_SALT:-tobemodifiedsalt}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET:-tobemodifiedjwt}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT:-tobemodifiedtransfer}
      JWT_SECRET: ${JWT_SECRET:-tobemodifiedjwtsecret}
    volumes:
      - ./backend/database:/opt/app/database
      - ./backend/public/uploads:/opt/app/public/uploads
    ports:
      - "1337:1337"

  nuxt:
    image: ghcr.io/${REPO_OWNER:-mfaris2002}/portfolio-nuxt:latest
    container_name: portfolio-nuxt
    restart: always
    environment:
      NODE_ENV: production
      STRAPI_URL: http://strapi:1337
    ports:
      - "3000:3000"
    depends_on:
      - strapi
